all:
  children:
    db:
      hosts:
        db-node:
          ansible_ssh_user: root
          ansible_ssh_host: 5.35.98.1
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: /var/lib/gitlab-runner/.ssh/id_rsa

    apps:
      hosts:
        wp-1-node:
          ansible_ssh_user: root
          ansible_ssh_host: 83.136.232.178
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: /var/lib/gitlab-runner/.ssh/id_rsa
        wp-2-node:
          ansible_ssh_user: root
          ansible_ssh_host: 92.63.106.105
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: /var/lib/gitlab-runner/.ssh/id_rsa

    monitoring:
      hosts:
        mon-node:
          ansible_ssh_user: root
          ansible_ssh_host: 92.63.106.241
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: /var/lib/gitlab-runner/.ssh/id_rsa

    balancer:
      hosts:
        bln-node:
          ansible_ssh_user: root
          ansible_ssh_host: 92.63.106.127
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: /var/lib/gitlab-runner/.ssh/id_rsa
