---
- name: Добавление правил для синхронизации
  when: inventory_hostname in groups['apps']
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    source: "{{ item }}"
    destination_port: "22"
    jump: ACCEPT
    state: absent
  with_items:
    - 10.0.0.25
    - 10.0.0.4
- name: Запретить весь трафик с балансировщика на сервер базы данных
  when: inventory_hostname in groups['monitoring']
  iptables:
    chain: "{{ item }}"
    protocol: all
    source: 0.0.0.0
    destination: 10.0.1.16
    jump: DROP
    state: absent
  with_items:
    - OUTPUT
    - INPUT
- name: Запретить входящие соединения ssh
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    jump: DROP
    state: absent
- name: Сохранить
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables

