---
- name: Добавление публичных ssh ключей
  authorized_key:
    user: "{{ ssh_remote_user_add }}"
    key: "{{ item }}"
    state: present
  with_items:
    - "{{ ssh_user1_key }}"
    - "{{ ssh_user2_key }}"
  tags:
    - add