---
- name: Install Zabbix repository key
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present
- name: Add Zabbix APT repository
  apt_repository:
    repo: 'deb https://repo.zabbix.com/zabbix/6.0/ubuntu focal main'
    state: present
- name: Обновить пакеты Ubuntu
  apt:
    update_cache: true
- name: Установка mс,htop,iotop,iptables-persistent,zabbix-agent,rsync
  when: inventory_hostname != 'db-node'
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mc
    - htop
    - iotop
    - iptables-persistent
    - zabbix-agent
    - rsync
- name: Установка zabbix-agent2 на db-node
  when: inventory_hostname == 'db-node'
  apt:
    name: zabbix-agent2
    state: present
